version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    hostname: localhost
    network_mode: "host"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  mongodb:
    image: mongo:latest
    container_name: mongo-container
    hostname: localhost
    network_mode: "host"
    ports:
      - 27017:27017

  user-service:
    container_name: user-service
    build: user-service/
    hostname: localhost
    network_mode: "host"
    ports:
      - 8011:8011
    depends_on:
      - eureka-server
    restart: always

  login-service:
    container_name: login-service
    build: login-service/
    hostname: localhost
    network_mode: "host"
    depends_on:
      - eureka-server
    ports:
      - 8007:8007
    restart: always

  booking-service:
    container_name: booking-service
    build: booking-service/
    hostname: localhost
    network_mode: "host"
    ports:
      - 8003:8003
    depends_on:
      - eureka-server
    restart: always

  ground-service:
    container_name: ground-service
    build: ground-service/
    hostname: localhost
    network_mode: "host"
    ports:
      - 8007:8007
    depends_on:
      - eureka-server
    restart: always


  payment-service:
    container_name: payment-service
    build: payment-service/
    hostname: localhost
    network_mode: "host"
    depends_on:
      - eureka-server
    ports:
      - 8009:8009
    restart: always

  eureka-server:
    build: eureka-server/
    container_name: eureka-server
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8761:8761

  apigateway:
    build: api-gateway/
    container_name: apigateway
    depends_on:
      - eureka-server
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8091:8091

  product-webapp-service:
    build: product-webapp-service/
    image: product-webapp-service
    restart: always
    container_name: product-webapp-service
    network_mode: "host"
    hostname: localhost
    ports:
      - 8013:8013

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181




